const commandNameList = {

  SOFTWARE_CRC: 'SOFTWARE_CRC',
  NUMBER_OF_ACCEPTOR_RESETS: 'NUMBER_OF_ACCEPTOR_RESETS',
  ACCEPTOR_TYPE: 'ACCEPTOR_TYPE',
  ACCEPTOR_SERIAL_NUMBER: 'ACCEPTOR_SERIAL_NUMBER',
  ACCEPTOR_BOOT_SOFTWARE_VERSION: 'ACCEPTOR_BOOT_SOFTWARE_VERSION',
  ACCEPTOR_APPLICATION_SOFTWARE_VERSION: 'ACCEPTOR_APPLICATION_SOFTWARE_VERSION',
  ACCEPTOR_VARIANT_NAME: 'ACCEPTOR_VARIANT_NAME',
  ACCEPTOR_VARIANT_VERSION: 'ACCEPTOR_VARIANT_VERSION',
  ACCEPTOR_AUDIT_LIFE_TIME_TOTALS: 'ACCEPTOR_AUDIT_LIFE_TIME_TOTALS',
  ACCEPTOR_AUDIT_QP_MEASURES: 'ACCEPTOR_AUDIT_QP_MEASURES',
  ACCEPTOR_AUDIT_GENERAL_PERFORMANCE_MEASURES: 'ACCEPTOR_AUDIT_GENERAL_PERFORMANCE_MEASURES',
  QUERY_EXPANDED_NOTE_SPECIFICATION: 'QUERY_EXPANDED_NOTE_SPECIFICATION',
  CASH_VALUE_IN_CASSETTE: 'CASH_VALUE_IN_CASSETTE',
  CLEAR_CASH_VALUE_IN_CASSETTE: 'CLEAR_CASH_VALUE_IN_CASSETTE',

  SOFT_RESET: 'SOFT_RESET',
  SETUP: 'SETUP',
  ENABLE: 'ENABLE',
  DISABLE: 'DISABLE',
  POLL: 'POLL',
  STACK: 'STACK',
  RETURN: 'RETURN',

};

export default  commandNameList;
