const eventNameList = {
  OPEN: 'OPEN',
  CLOSE: 'CLOSE',
  IDLING: 'IDLING',
  ACCEPTING: 'ACCEPTING',
  ESCROWED: 'ESCROWED', /// pul olindi lekin qopga tushmadi
  STACKING: 'STACKING',
  STACKED: 'STACKED',
  RETURNING: 'RETURNING', // qaytarilmoqda
  RETURNED: 'RETURNED', // qaltarildi
  CHEATED: 'CHEATED',
  REJECTED: 'REJECTED',
  JAMMED: 'JAMMED',
  CASSETTE_FULL: 'CASSETTE_FULL',
  LRC_REMOVED: 'LRC_REMOVED',
  PAUSED: 'PAUSED',
  CALIBRATION: 'CALIBRATION',
  POWER_UP: 'POWER_UP',
  INVALID_COMMAND: 'INVALID_COMMAND', //
  FAILURE: 'FAILURE',
  NO_PUSH_MODE: 'NO_PUSH_MODE',
  FLASH_DOWNLOAD: 'FLASH_DOWNLOAD',
  PRESTACK: 'PRESTACK',
  ERROR: 'ERROR',
};

module.exports = eventNameList;
